# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_auto_20160926_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Only you can see this'),
        ),
    ]
