# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(help_text='Markdown flavoured'),
        ),
    ]
