# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0016_auto_20161028_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.CharField(choices=[('foyer', 'Foyer'), ('d105', 'Main (D105)'), ('d0206', 'Right (D0206)'), ('d0207', 'Left (D0207)'), ('a112', 'A112'), ('a113', 'A113')], max_length=5),
        ),
    ]
