# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0019_speaker_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ('title',)},
        ),
    ]
