# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0020_auto_20170507_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ('date', 'room')},
        ),
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Big hall'), (2, 'Theatre'), (3, 'Foyer')]),
        ),
    ]
