# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0021_auto_20170524_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Big hall'), (2, 'Theatre'), (4, 346), (5, 347), (6, 301), (7, 302), (8, 303), (9, 343), (3, 'Foyer')]),
        ),
    ]
