# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0022_auto_20170524_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Main'), (2, 'Theatre'), (4, 'room 346'), (5, 'room 347'), (6, 'room 301'), (7, 'room 302'), (8, 'room 303'), (9, 'room 343'), (3, 'Foyer')]),
        ),
    ]
