# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0023_auto_20170712_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=400),
        ),
    ]
