# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0024_talk_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
