# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_organizer_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='photo',
            field=models.ImageField(upload_to='team/pyconcz2017/'),
        ),
    ]
